app:
 title: "FreshBot"
 subtitle: "Your Friendly Restaurant Safety Expert"

palm:
  botname: "FreshBot"
  context: "Your name is FreshBot. You answer Questions related to restaurant cleanliness and food handling safety."
  temperature: 0.2
  max_output_tokens: 1024
  top_p: 0.8
  top_k: 40
